//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appharbor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sapEntities : DbContext
    {
        public sapEntities()
            : base("name=sapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int OCRD_Delete(string cardcode, string cardname, string address)
        {
            var cardcodeParameter = cardcode != null ?
                new ObjectParameter("cardcode", cardcode) :
                new ObjectParameter("cardcode", typeof(string));
    
            var cardnameParameter = cardname != null ?
                new ObjectParameter("cardname", cardname) :
                new ObjectParameter("cardname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OCRD_Delete", cardcodeParameter, cardnameParameter, addressParameter);
        }
    
        public virtual int OCRD_Exists(string cardcode, string cardname, string address, ObjectParameter exists)
        {
            var cardcodeParameter = cardcode != null ?
                new ObjectParameter("cardcode", cardcode) :
                new ObjectParameter("cardcode", typeof(string));
    
            var cardnameParameter = cardname != null ?
                new ObjectParameter("cardname", cardname) :
                new ObjectParameter("cardname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OCRD_Exists", cardcodeParameter, cardnameParameter, addressParameter, exists);
        }
    
        public virtual int OCRD_Insert(string cardcode, string cardname, string address)
        {
            var cardcodeParameter = cardcode != null ?
                new ObjectParameter("cardcode", cardcode) :
                new ObjectParameter("cardcode", typeof(string));
    
            var cardnameParameter = cardname != null ?
                new ObjectParameter("cardname", cardname) :
                new ObjectParameter("cardname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OCRD_Insert", cardcodeParameter, cardnameParameter, addressParameter);
        }
    
        public virtual ObjectResult<OCRD_Select_Result> OCRD_Select(string cardcode, string cardname, string address)
        {
            var cardcodeParameter = cardcode != null ?
                new ObjectParameter("cardcode", cardcode) :
                new ObjectParameter("cardcode", typeof(string));
    
            var cardnameParameter = cardname != null ?
                new ObjectParameter("cardname", cardname) :
                new ObjectParameter("cardname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OCRD_Select_Result>("OCRD_Select", cardcodeParameter, cardnameParameter, addressParameter);
        }
    
        public virtual int OCRD_Update(string cardcode, string cardname, string address)
        {
            var cardcodeParameter = cardcode != null ?
                new ObjectParameter("cardcode", cardcode) :
                new ObjectParameter("cardcode", typeof(string));
    
            var cardnameParameter = cardname != null ?
                new ObjectParameter("cardname", cardname) :
                new ObjectParameter("cardname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OCRD_Update", cardcodeParameter, cardnameParameter, addressParameter);
        }
    }
}
